CREATE TABLE CATEGORIES(
	CATEGORY_ID 	INT		NOT NULL,
	CATEGORY_NAME	TEXT     NOT NULL
);

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (19128, 'Ice Skating');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (132119, 'Music');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (74032, 'Sports');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (92310, 'Theater');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (2031, 'Academic');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (48732, 'Art');

INSERT INTO CATEGORIES (CATEGORY_ID,CATEGORY_NAME)
VALUES (84309, 'Town');