CREATE TABLE ORGS(
	ORG_ID 			INT		NOT NULL,
	ORG_NAME		TEXT     NOT NULL
);

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (16216193, 'PUFSC');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (222015, 'VTone');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (1820, 'R20');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (3029, 'PPE');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (5201, 'PUWRFC');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (5662, 'Princeton Football');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (20391, 'Rise Up Singing');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (29104, 'Princeton Triangle Club');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (321, 'Department of Mechanical & Aerospace Engineering');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (168, 'PU Art Museum');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (146, 'Palmer Square');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (9875, 'Department of Music');

INSERT INTO ORGS (ORG_ID,ORG_NAME)
VALUES (68786, 'McCarter Theatre Center');
