# Generated by Django 2.1.2 on 2018-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
