# Generated by Django 2.1.2 on 2018-12-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20181110_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorite_users',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(default=1, to='calendarapp.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Organization'),
        ),
    ]
