# Generated by Django 2.1.2 on 2018-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_auto_20181207_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='favorite_users',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_events',
            field=models.ManyToManyField(to='calendarapp.Event'),
        ),
    ]
