# Generated by Django 2.1.2 on 2018-12-21 23:14

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='GMT'),
        ),
    ]
