# Generated by Django 2.1.2 on 2019-01-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_auto_20190108_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
