# Generated by Django 2.1.2 on 2019-01-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_auto_20190108_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
